alloy:
  global:
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 12345
      runAsGroup: 12345

  alloy:
    configMap:
      create: false
      name: platform-alloy-logs

    enableReporting: false
    mounts:
      dockercontainers: true
      extra:
        - name: tmp
          readOnly: false
          mountPath: /tmp
        # - mountPath: /secret
        #   name: alloy-loki-gateway-password-volume
        #   readOnly: true

    resources:
      requests: { cpu: 1m, memory: 128Mi }
      limits: { cpu: 1000m, memory: 256Mi }

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      privileged: false
      readOnlyRootFilesystem: true

  controller:
    volumes:
      extra:
        - name: tmp
          emptyDir: {}
        # - name: alloy-loki-gateway-password-volume
        #   secret:
        #     secretName: alloy-loki-gateway-password

  # Options for the extra controller used for config reloading.
  configReloader:
    enabled: true

    resources:
      requests: { cpu: 1m, memory: 16Mi }
      limits: { cpu: 100m, memory: 16Mi }

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      privileged: false
      readOnlyRootFilesystem: true

  ingress:
    enabled: true
    ingressClassName: kubelb
    annotations:
      kubelb.k8c.io/manage-certificates: "true"
    hosts:
      - "alloy-logs.l7.test2-dev-bs.kkp.lab2.cid"
    tls:
      - hosts:
          - "alloy-logs.l7.test2-dev-bs.kkp.lab2.cid"
        secretName: "alloy-logs.l7.test2-dev-bs.kkp.lab2.cid-tls"
