kind: Secret
apiVersion: v1
metadata:
  labels:
    grafana-datasource: "true"
  name: platform-loki-grafana-datasource
  namespace: platform
type: Opaque
stringData:
  loki.yaml: |
    apiVersion: 1
    datasources:
      # see https://grafana.com/docs/grafana/latest/datasources/loki/
      - name: Platform Loki
        type: loki
        access: proxy
        uid: platform-loki
        url: http://loki-gateway.platform
        # basicAuth: true
        # basicAuthUser: "grafana-loki"
        jsonData:
          httpHeaderName1: X-Scope-OrgID
          maxLines: 1000
        secureJsonData:
          httpHeaderValue1: "1"
          # basicAuthPassword: "bmljZS10cnk="
